/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RhCommandCenterRouteImport } from './routes/rh.command-center'
import { Route as RhCollaborateursIndexRouteImport } from './routes/rh.collaborateurs.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhCommandCenterRoute = RhCommandCenterRouteImport.update({
  id: '/rh/command-center',
  path: '/rh/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const RhCollaborateursIndexRoute = RhCollaborateursIndexRouteImport.update({
  id: '/rh/collaborateurs/',
  path: '/rh/collaborateurs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rh/command-center': typeof RhCommandCenterRoute
  '/rh/collaborateurs/': typeof RhCollaborateursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rh/command-center': typeof RhCommandCenterRoute
  '/rh/collaborateurs': typeof RhCollaborateursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rh/command-center': typeof RhCommandCenterRoute
  '/rh/collaborateurs/': typeof RhCollaborateursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rh/command-center' | '/rh/collaborateurs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rh/command-center' | '/rh/collaborateurs'
  id: '__root__' | '/' | '/rh/command-center' | '/rh/collaborateurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RhCommandCenterRoute: typeof RhCommandCenterRoute
  RhCollaborateursIndexRoute: typeof RhCollaborateursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/command-center': {
      id: '/rh/command-center'
      path: '/rh/command-center'
      fullPath: '/rh/command-center'
      preLoaderRoute: typeof RhCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/collaborateurs/': {
      id: '/rh/collaborateurs/'
      path: '/rh/collaborateurs'
      fullPath: '/rh/collaborateurs/'
      preLoaderRoute: typeof RhCollaborateursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RhCommandCenterRoute: RhCommandCenterRoute,
  RhCollaborateursIndexRoute: RhCollaborateursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
